<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sds.platform</groupId>
        <artifactId>sds-platform</artifactId>
        <version>0.0.3</version>
    </parent>

    <artifactId>sds-integration-commons</artifactId>

    <dependencies>
        <!-- TESTING -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>